---

- name: Echo
  hosts: "{{host}}"
  vars:
    extracted_hosts: "{{host}}"
  tasks:
  - name: ansible create directory example
    file:
      path: /tmp/Civkule/java_dns
      state: directory
  - name: ansible create gradle
    file:
      path: /tmp/Civkule/gradle
      state: directory
    when: extracted_hosts == "backEndServers"
  - name: download sources
    get_url: url=https://repo1.maven.org/maven2/dnsjava/dnsjava/3.5.0/dnsjava-3.5.0.jar dest=/tmp/test/java_dns
  - name: download gradle
    get_url: url=https://services.gradle.org/distributions/gradle-8.0-milestone-2-docs.zip dest=/tmp/Civkule
  - name: Unarchive a file that is already on the remote machine
    ansible.builtin.unarchive: src=/tmp/Civkule/gradle-8.0-milestone-2-docs.zip dest=/tmp/Civkule/gradle remote_src=yes
    when: extracted_hosts == "backEndServers"
